baseURL = 'https://faisalkhan.com'
languageCode = 'en-us'
title = 'Faisal Khan LLC'
theme = "PaperMod"

# Enable emoji support
enableEmoji = true
# Enable syntax highlighting
pygmentsUseClasses = true
# Enable RSS
enableRobotsTXT = true

# Pagination
[pagination]
  pagerSize = 10

# Taxonomies (categories and tags)
[taxonomies]
  category = "categories"
  tag = "tags"
  jurisdiction = "jurisdictions"
  service = "services"

# TOP NAVIGATION MENU
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "solutions"
    name = "Solutions"
    url = "/solutions/"
    weight = 30

  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources/"
    weight = 40

  [[menu.main]]
    identifier = "clients"
    name = "Clients"
    url = "/clients/"
    weight = 50

  [[menu.main]]
    identifier = "pricing"
    name = "Pricing"
    url = "/pricing/"
    weight = 60

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 70

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 80

# BOTTOM NAVIGATION MENU (Footer)
  [[menu.footer]]
    identifier = "book-call"
    name = "Book A Call"
    url = "/book-a-call/"
    weight = 10

  [[menu.footer]]
    identifier = "legal-disclaimer"
    name = "Legal Disclaimer"
    url = "/legal/disclaimer/"
    weight = 20

  [[menu.footer]]
    identifier = "privacy-policy"
    name = "Privacy Policy"
    url = "/legal/privacy/"
    weight = 30

  [[menu.footer]]
    identifier = "terms-service"
    name = "Terms of Service"
    url = "/legal/terms/"
    weight = 40

  [[menu.footer]]
    identifier = "refund"
    name = "Refund"
    url = "/legal/refund/"
    weight = 50

  [[menu.footer]]
    identifier = "support"
    name = "Support"
    url = "/support/"
    weight = 60

  [[menu.footer]]
    identifier = "sitemap"
    name = "Sitemap"
    url = "/sitemap/"
    weight = 70

# PaperMod theme specific parameters
[params]
  # Site identity
  author = "Faisal Khan"
  description = "Cross-border payments, banking access, licensing, and crypto compliance consulting"
  
  # Social and contact
  email = "your-email@faisalkhan.com"
  
  # Theme settings
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowToc = true
  TocOpen = false
  
  # Custom CSS
  assets = {css = ["css/custom.css"]}
  
  # Search
  disableFingerprinting = false
  
  # SEO and analytics
  googleAnalytics = "G-XXXXXXXXXX"
  
  # Social media profiles
  [params.profileMode]
    enabled = false
    
  # Home page settings
  [params.homeInfoParams]
    Title = "Faisal Khan LLC"
    Content = "Expert consulting in cross-border payments, banking access, licensing, and crypto compliance. Helping businesses navigate regulated financial services globally."

  # Footer social links
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/faisalkhan"
  
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/faisalkhan"

# Markup configuration for proper rendering
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true

# Output formats (for RSS, search, etc.)
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

# Related content configuration
[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 80
  [[related.indices]]
    name = "jurisdictions"
    weight = 60

# Sitemap configuration
[sitemap]
  changefreq = "weekly"
  priority = 0.5