[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.2"

[context.production.environment]
  HUGO_ENV = "production"

# PERFORMANCE OPTIMIZATIONS

# Enable gzip compression for all file types
[[headers]]
  for = "/*"
  [headers.values]
    # Enable compression
    Content-Encoding = "gzip"
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets for 1 year
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML pages for 1 hour (shorter cache for content updates)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Cache root page for 1 hour
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Preload critical resources
[[headers]]
  for = "/"
  [headers.values]
    Link = '''</css/extended/blank.css>; rel=preload; as=style,
              </images/faisal-khan-banking-payments.webp>; rel=preload; as=image'''

# Force HTTPS redirects (avoid redirect performance hit)
[[redirects]]
  from = "http://faisalkhanllc.xyz/*"
  to = "https://faisalkhanllc.xyz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.faisalkhanllc.xyz/*"
  to = "https://faisalkhanllc.xyz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.faisalkhanllc.xyz/*"
  to = "https://faisalkhanllc.xyz/:splat"
  status = 301
  force = true