---
title: "How to Start a Money Transfer Business – Video Series Playlist"
date: "2021-06-24"
url: "/solutions/licensing/money-transmitter-license-mtl/how-to-start-a-money-transfer-business-video-series-playlist/"
draft: false
description: "Welcome to a video series I am putting together on _how to start a money transfer business_. It seems folks don't have too much time to read lengthy a..."
---

Welcome to a video series I am putting together on _how to start a money transfer business_. It seems folks don't have too much time to read lengthy articles or other blog posts, so I thought I'd give it a try by putting up small (read: short) videos that explain some of the nuances. Needless to say, you can argue, each video left this out or left that out. That is true. Even though as small of a subject each video discusses, it is in NO way complete. There is so much information out there, I am not sure if I or anyone else would be able to compile it together. 

Nonetheless, this is a small endeavour to try to achieve just that.

##  Introduction - Watch This First 

https://www.youtube.com/watch?v=qOF6ivYwCUo 

##  Starting Out? Learn the basics

  * [How To Start A Money Transfer Business? YouTube Series (Intro video)](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-youtube-series/)
  * [Financing – How are you getting the money to start this? Friends or Family?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-financing-tip/)
  * [Monetary Requirement – How much money is required to start it?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-budget-tip/)
  * [What “problem” are you trying to solve?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-problem-tip/)
  * [Build versus Lease versus Buy – Which one is the right choice?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-build-versus-lease-tip/)
  * [Banking, License, Compliance, and Regulations!](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-compliance-law-tip/)
  * [What Are Remittances?](https://faisalkhan.com/video/what-are-remittances/)
  * [Why Are Remittances Important?](https://faisalkhan.com/video/why-are-remittances-important/)
  * [What is an ISO and what do they do?](https://faisalkhan.com/video/what-is-an-iso-and-what-does-it-do/)
  * [What is a Flow of Funds (Time Motion Diagram)](https://faisalkhan.com/video/what-is-a-flow-of-funds-or-fof-for-short/)
  * [What is Passporting?](https://faisalkhan.com/video/what-is-passporting/)
  * [What is KYC?](https://faisalkhan.com/video/what-is-kyc-know-your-customer/)
  * [What is KYB?](https://faisalkhan.com/video/what-is-kyb-know-your-business/)
  * [Your Business Intelligence Plan?](https://faisalkhan.com/video/your-business-intelligence-plan/)
  * [How to Validate your Problem & Solution Via Field Research?](https://faisalkhan.com/video/how-to-validate-your-problem-solution-via-field-research/)
  * [What is a Term Sheet?](https://faisalkhan.com/video/what-is-a-term-sheet/)
  * [What Is Source Of Funds (SOF)?](https://faisalkhan.com/video/what-is-source-of-funds-sof/)
  * [What is Aggregation and How does it Work in the World of Money Transfer?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/what-is-aggregation-and-how-does-it-work-in-the-world-of-money-transfer/)
  * [What is Liquidity?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/what-is-liquidity/)
  * [What Is The Travel Rule?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/what-is-the-travel-rule/)
  * [Money Transfer as a Service (MTaaS) – General Presentation](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/money-transfer-as-a-service-mtaas-general-presentation/)
  * [Explanation of Cross Border Money Transfer (Pre-Funded and Non-Pre-Funded)](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/explanation-of-cross-border-money-transfer-pre-funded-and-non-pre-funded/)
  * [Example of Money Transfer from US to UK. Walk Through Description](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/example-of-money-transfer-from-us-to-uk-walk-through-description/)
  * [Currency Cross Rate! What Is It?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/currency-cross-rate-what-is-it/)
  * [What Is The Mid-Market Rate (or the Interbank rate)? Why Is It Important?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/what-is-the-mid-market-rate-or-the-interbank-rate-why-is-it-important/)
  * [What Are Exotic Currencies? Why Are They Called Exotic To Begin With?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/what-are-exotic-currencies-why-are-they-called-exotic-to-begin-with/)
  * [What is a UBO (Ultimate Beneficial Owner)?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/what-is-a-ubo-ultimate-beneficial-owner/)
  * [How To Start A Money Transfer Business? (Updated Intro Message)](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/how-to-start-a-money-transfer-business-updated-intro-message/)

## Licensing

  * [Difference between MTL and MSB?](https://faisalkhan.com/video/difference-between-mtl-and-msb/)
  * [What is Money Transmitter License and How Can You Get One?](https://faisalkhan.com/video/what-is-money-transmitter-license-and-how-can-you-get-one/)
  * [Do I Need A License To Start A Money Transfer Service?](https://faisalkhan.com/video/do-i-need-a-license-to-start-a-money-transfer-service/)
  * [How many Money Transmitter Licenses do I require if I have to do business in the US?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/how-many-money-transmitter-licenses-do-i-require-if-i-have-to-do-business-in-the-us/)
  * [Licensing: Agent vs. Program Manager](https://faisalkhan.com/video/licensing-agent-vs-program-manager/)
  * [How will you operate? As a License Holder or as an ISO?](https://faisalkhan.com/video/how-will-you-operate-as-a-license-holder-or-as-an-iso/)
  * [What Is A Decent Revenue Share For Using Someone Else’s License For Regulatory Coverage?](https://faisalkhan.com/video/what-is-a-decent-revenue-share-for-using-someone-elses-license-for-regulatory-coverage/)
  * [Why Do You Need a Money Transmitter License If You Are Licensed Outside the U.S.?](https://faisalkhan.com/video/why-do-you-need-a-money-transmitter-license-if-you-are-licensed-outside-the-us/)
  * [How Much Do Money Transmitter Licenses Cost?](https://faisalkhan.com/video/how-much-do-money-transmitter-licenses-cost/)
  * [What Does A Program Manager Do?](https://faisalkhan.com/video/what-does-a-program-manager-do/)
  * [What Is A Program Manager? (Part II)](https://faisalkhan.com/video/what-is-a-program-manager-part-ii/)
  * [FinCEN Registration & Money Transmitter Licenses](https://faisalkhan.com/video/fincen-registration-money-transmitter-licenses/)
  * [Is FinCEN Registration Free or Not?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/is-fincen-registration-free-or-not/)
  * [Why FinCEN Registration is NOT a License?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/why-fincen-registration-is-not-a-license/)
  * [Unlicensed Money Transfer! What to do next?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/unlicensed-money-transfer-what-to-do-next/)
  * [3rd Party Payment Apps? It Might Be Illegal To Use Them!](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/3rd-party-payment-apps-it-might-be-illegal-to-use-them/)
  * [Difference Between An Authorized Delegate vs Non-Authorized Delegate](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/difference-between-an-authorized-delegate-vs-non-authorized-delegate/)
  * [I have an idea for an app. Do I need a license to send money all over the world?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/i-have-an-idea-for-an-app-do-i-need-a-license-to-send-money-all-over-the-world/)
  * [Buying a UK SPI License? Consider this!](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/buying-a-uk-spi-license-consider-this/)
  * [Working with an EMI license and becoming an EMD Agent](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/working-with-an-emi-license-and-becoming-an-emd-agent/)
  * [Nationwide Coverage vs. Must-Have States?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/nationwide-coverage-vs-must-have-states/)
  * [Want To Get Your Own EMI Or Become An EMI Agent? Consider This.](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/want-to-get-your-own-emi-or-become-an-emi-agent-consider-this/)
  * [Leveraging A License](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/leveraging-a-license/)
  * [Single-State License In the United States – What Can You Do With It?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/single-state-license-in-the-united-states-what-can-you-do-with-it/)
  * [Difference Between EMD (Registered Agent) and Sponsorship](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/difference-between-emd-registered-agent-and-sponsorship/)
  * [Difference between an API and an EMI](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/difference-between-an-api-and-an-emi/)
  * [What is a Program Manager? (Updated)](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/what-is-a-program-manager-updated/)

## Banking

  * [What is a Correspondent Tie-Up Agreement?](https://faisalkhan.com/video/what-is-a-correspondent-tie-up-agreement/)
  * [What is a Pre-funded Account?](https://faisalkhan.com/video/what-is-a-prefunded-account/)
  * [What is a Payout Partner?](https://faisalkhan.com/video/what-is-a-payout-partner/)
  * [What is a Good Funds Settled Model?](https://faisalkhan.com/video/what-is-a-good-funds-settled-model/)
  * [What is a Payment Account?](https://faisalkhan.com/video/what-is-a-payment-account/)
  * [What is Pre-Funding and How Does it Work? ](https://faisalkhan.com/video/what-is-pre-funding-and-how-does-it-work/)
  * [What is a Reserve Account?](https://faisalkhan.com/video/what-is-a-reserve-account/)
  * [What Is An FBO (For Benefit Of) Account?](https://faisalkhan.com/video/what-is-an-fbo-for-benefit-of-account/)
  * [What is Netting Off and How Does it Work?](https://faisalkhan.com/video/what-is-netting-off-and-how-does-it-work/)
  * [What is a Correspondent Tie-up? & Why is it Necessary?](https://faisalkhan.com/video/what-is-a-correspondent-tie-up-why-is-it-necessary/)
  * [What is a Tri-Party Correspondent Tie-Up Agreement?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/what-is-a-tri-party-correspondent-tie-up-agreement/)
  * [As a Licensed MTO Can You Operate A Bank Account Outside In Another Country?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/as-a-licensed-mto-can-you-operate-a-bank-account-outside-in-another-country/)
  * [What If Banks Decide To Close My Account After The Account Has Been Active For Some Time?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/what-if-banks-decide-to-close-my-account-after-the-account-has-been-active-for-some-time/)
  * [BYOB – Build Your Own Bank! (Video: 1 of 3)](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/byob-build-your-own-bank-video-1-of-3/)
  * [BYOB – Build Your Own Bank! (Video: 2 of 3)](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/byob-build-your-own-bank-video-2-of-3/)
  * [BYOB – Build Your Own Bank (Video: 3 of 3)](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/byob-build-your-own-bank-video-3-of-3/)
  * [Need Pre-funding Money for your Money Transfer business?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/need-pre-funding-money-for-your-money-transfer-business/)
  * [Build Your Own Bank As A Service (BYOBaaS)](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/build-your-own-bank-as-a-service-byobaas/)
  * [Understanding Merchant Account Zones for Acquiring](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/understanding-merchant-account-zones-for-acquiring/)
  * [Flow of Funds for Correspondent Accounts (for Remittance as a Service) – USA Only](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/flow-of-funds-for-correspondent-accounts-for-remittance-as-a-service-usa-only/)
  * [Merchant Account! You Cannot Just Get It – You Have To Apply And Qualify For It](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/merchant-account-you-cannot-just-get-it-you-have-to-apply-and-qualify-for-it/)
  * [Want To Build A Neo Bank?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/want-to-build-a-neo-bank/)
  * [Card Acquiring Options for Money Transfer Operators](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/card-acquiring-options-for-money-transfer-operators/)

## Remittances

  * [How Big is the P2P Remittance Market?](https://faisalkhan.com/video/how-big-is-the-p2p-remittance-market/)
  * [How Big is the B2B Market?](https://faisalkhan.com/video/how-big-is-the-b2b-business-to-business-market/)
  * [What is a Corridor Killer?](https://faisalkhan.com/video/what-is-a-corridor-killer/)
  * [Negotiating with a Financial Institution – Are You a Good Negotiator?](https://faisalkhan.com/video/negotiating-with-a-financial-institution/)
  * [Are You A Fintech That Is Going From Zero to One?](https://faisalkhan.com/video/are-you-a-fintech-that-is-going-from-zero-to-one/)
  * [What is Remittance-As-A-Service (RaaS)?](https://faisalkhan.com/video/what-is-remittance-as-a-service-raas/)
  * [What are the Pros and Cons of RaaS (Remittance-as-a-Service)?](https://faisalkhan.com/video/what-are-the-pros-and-cons-of-raas-remittance-as-a-service/)
  * [How Much Does Remittance-As-A-Service (RaaS) Cost?](https://faisalkhan.com/video/how-much-does-remittance-as-a-service-raas-cost/)
  * [How Much Do I Charge For RaaS Consulting?](https://faisalkhan.com/video/how-much-do-i-charge-for-raas-consulting/)
  * [What Does The Value Added Payment Stack in Remittances Look Like?](https://faisalkhan.com/video/what-does-the-value-added-payment-stack-in-remittances-look-like/)
  * [Why Value-Added Payments In Remittances Reduces Financial Misappropriation?](https://faisalkhan.com/video/why-value-added-payments-in-remittances-reduces-financial-misappropriation/)
  * [How Long Does It Take To Setup A Remittance-As-A-Service Solution?](https://faisalkhan.com/video/how-long-does-it-take-to-setup-a-remittance-as-a-service-solution/)
  * [Is It Possible To Have Real Time Transfers in Money Transfer World?](https://faisalkhan.com/video/is-it-possible-to-have-real-time-transfers-in-money-transfer-world/)
  * [How Big Is The Real Time Payments Economy in the Money Transfer World?](https://faisalkhan.com/video/how-big-is-the-real-time-payments-economy-in-the-money-transfer-world/)
  * [Is There Fraud In The Money Transfer Industry?](https://faisalkhan.com/video/is-there-fraud-in-the-money-transfer-industry/)
  * [What is Hawala (or Hundi)?](https://faisalkhan.com/video/what-is-hawala-or-hundi/)
  * [What is Hawala? (Part Two)](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/what-is-hawala-part-2/)
  * [What are Official and Unofficial Remittances?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/what-are-official-and-unofficial-remittances/)
  * [The Case For Small Value Remittances](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/the-case-for-small-value-remittances/)
  * [How Does Hawala Work? How In A Few Minutes, You Can Get Money Across The World, In Your Hotel Room!](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/how-does-hawala-work-how-in-a-few-minutes-you-can-get-money-across-the-world-in-your-hotel-room/)
  * [Who Pays for the Remittance Fees Customer or MTO?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/how-to-start-a-money-transfer-business-youtube-series/who-pays-for-the-remittance-fees-customer-or-mto/)
  * [Real-Time Payments The Trillion Dollar Opportunity](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/real-time-payments-the-trillion-dollar-opportunity-seriously/)
  * [Interoperability in Payments](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/interoperability-in-payments/)
  * [Value Addition in Money Transfers (Remittances)](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/value-addition-in-money-transfers-remittances/)
  * [Interoperability between Wallets and Stored Value Systems](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/interoperability-between-wallets-and-stored-value-systems/)
  * [Super APIs. What the heck are they?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/super-apis-what-the-heck-are-they/)
  * [Quick Understanding of Hyperlocal Payments](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/quick-understanding-of-hyperlocal-payments/)
  * [Difference between an Aggregator and a Super API](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/difference-between-an-aggregator-and-a-super-api/)
  * [Let’s talk about Somalia](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/lets-talk-about-somalia/)
  * [Where Does Your Company Need To Be Registered (For RAAS)?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/where-does-your-company-need-to-be-registered-for-raas/)
  * [You Do Not Have To Be Afraid Of RaaS From The United States](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/you-do-not-have-to-be-afraid-of-raas-from-the-united-states/)
  * [Let Us Talk About Turkey Versus UAE: Who Is Winning The Money-Transfer Game?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/let-us-talk-about-turkey-versus-uae-who-is-winning-the-money-transfer-game/)
  * [Want to start a Money Transfer Company? Have You Considered RaaS?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/want-to-start-a-money-transfer-company-have-you-considered-raas/)
  * [The Next Big Thing? Micropayments!](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/the-next-big-thing-micropayments/)
  * [The Brick Equation](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/the-brick-equation/)
  * [How Big Is The B2B Market Compared To The P2P Market?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/how-big-is-the-b2b-market-compared-to-the-p2p-market/)
  * [How Big Is The Market Size For Small Value Transfers?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/how-big-is-the-market-size-for-small-value-transfers/)
  * [Percentage Only Transactions – Removing Network Access Charges](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/percentage-only-transactions-removing-network-access-charges/)
  * [Wallet vs. Remittances](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/wallet-vs-remittances/)
  * [Demo of White-Label, Skin-able, Mobile App for Remittances](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/demo-of-white-label-skin-able-mobile-app-for-remittances/)
  * [World Bank Data: Average Cost of Sending Remittances](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/world-bank-data-average-cost-of-sending-remittances/)
  * [Launching of new Remittance as a Service (RaaS) Pricing](https://www.youtube.com/watch?v=o6cFXhFowQ8)

## Cryptocurrency

  * [Remittances 2.0 – Crypto in remittances](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/remittances-2-0-crypto-in-remittances/)
  * [USA to Nigeria: Money Transfer using Bitcoins! (or any other country in Africa)](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/usa-to-nigeria-money-transfer-using-bitcoins-or-any-other-country-in-africa/)
  * [How Can A Traditional Money Transfer Business Get Started With Cryptocurrency For Remittances?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/how-can-a-traditional-money-transfer-business-get-started-with-cryptocurrency-for-remittances/)
  * [Got a Cryptocurrency Project? Think you’re exempt from licensing? Think again!](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/got-a-cryptocurrency-project-think-youre-exempt-from-licensing-think-again/)
  * [How Stable Coins Have Failed For Value Transfer In Cross Border Payments](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/how-stable-coins-have-failed-for-value-transfer-in-cross-border-payments/)
  * [Five Things You Can Do To Get Started With Crypto for Your Money Transfer Business – No Fluff!](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/five-things-you-can-do-to-get-started-with-crypto-for-your-money-transfer-business-no-fluff/)
  * [Don’t Fall For COVID19 Token / Coins for Remittances Scam!](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/dont-fall-for-coivid19-token-coins-for-remittances-scam/)
  * [What Happens When Central Bank Issued Digital Currency (CBDC) Comes Out?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/what-happens-when-central-bank-issued-digital-currency-cbdc-comes-out/)
  * [What Is A Collateralized Asset In The Digital/Crypto World?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/what-is-a-collateralized-asset-in-the-digital-crypto-world/)
  * [What I Think Of XRP](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/what-i-think-of-xrp/)
  * [Is XRP and RippleNet Going To Be Dominant And Be The Winner?](https://faisalkhan.com/video/is-xrp-and-ripplenet-going-to-be-dominant-and-be-the-winner/)
  * [Starting a Crypto-Related Money Transfer Business? Understand Regulations!](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/starting-a-crypto-related-money-transfer-business-understand-regulations/)

## Operations

  * [Is There Money To Be Made In The Money Transfer Business?](https://faisalkhan.com/video/is-there-money-to-be-made-in-the-money-transfer-business/)
  * [Is there Money To Be Made in the Money Transfer Business (Part II)?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/is-there-money-to-be-made-in-the-money-transfer-business-part-ii/)
  * [Are You A Small Money Transfer Operator? 12 Questions You Need To Ask Yourself.](https://faisalkhan.com/video/are-you-a-small-money-transfer-operator-12-questions-you-need-to-ask-yourself/)
  * [FinCEN MSB Definition for Transactions Under $1000 Per Person Per Day](https://faisalkhan.com/video/fincen-msb-definition-for-transactions-under-1000-per-person-per-day/)
  * [Are You A Small Independent Money Transfer Operator That Is Struggling?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/are-you-a-small-independent-money-transfer-operator-that-is-struggling/)
  * [Understanding Custody of Funds in Money Transfer / Remittances](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/understanding-custody-of-funds-in-money-transfer-remittances/)
  * [5 Questions Before Starting A Money Transfer Business to High-Risk Countries!](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/5-questions-before-starting-a-money-transfer-business-to-high-risk-countries/)
  * [10 Things to know before Starting your own Money Transfer Business!](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/10-things-to-know-before-starting-your-own-money-transfer-business/)
  * [FAQ on Money Transmitter License Sponsorship under an ISO Program for the United States](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/faq-on-money-transmitter-license-sponsorship-under-an-iso-program-for-the-united-states/)
  * [How to Build a Small Payments (Money Transfer) Company](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/how-to-build-a-small-payments-money-transfer-company/)
  * [7 Steps to Starting a Cross Border Payments Company](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/7-steps-to-starting-a-cross-border-payments-company/)
  * [Card Processing for your Money Transfer Business](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/how-to-start-a-money-transfer-business-youtube-series/card-processing-for-your-money-transfer-business/)
  * [As a Money Transfer Company… What are your Top 5 Problems?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/as-a-money-transfer-company-what-are-your-top-5-problems/)
  * [What is a Remittance Contract? …How Does It Work?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/what-is-a-remittance-contract-how-does-it-work/)
  * [Legal Contracts… Do You Have A Say In Them?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/legal-contracts-do-you-have-a-say-in-them/)
  * [Legal Opinion: Why Banks Do Not Provide Legal Opinion For Your Flow Of Funds Or Licensing?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/legal-opinion-why-banks-do-not-provide-legal-opinion-for-your-flow-of-funds-or-licensing/)
  * [EMI Agents & Restriction on Correspondent Agreements](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/emi-agents-restriction-on-correspondent-agreements/)
  * [How To Better Your Money Transfer Business During These Quarantined Times ](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/how-to-start-a-money-transfer-business-youtube-series/how-to-better-your-money-transfer-business-during-these-quarantined-times/)
  * [5 Things To Do Today To Better Your Money Transfer Business In The US](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/5-things-to-do-today-to-better-your-money-transfer-business-in-the-us/)
  * [How Do We Charge Our fees?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/how-do-we-charge-our-fees/)
  * [Volume Fees! What’s The Magic Number?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/volume-fees-whats-the-magic-number/)
  * [Why Do Prices Vary In Different Markets?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/why-do-prices-vary-in-different-markets/)
  * [Architecting A Mobile Wallet That Customers Want](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/architecting-a-mobile-wallet-that-customers-want/)
  * [So You Want To Start A Money Transfer Business?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/so-you-want-to-start-a-money-transfer-business/)
  * [Shall We Test Your Knowledge On Money Transfer?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/shall-we-test-your-knowledge-on-money-transfer/)
  * [12-Pivot Points for Money Transfer Operators](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/12-pivot-points-for-money-transfer-operators/)
  * [MLS Type Collaboration for Money Transfer Businesses](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/mls-type-collaboration-for-money-transfer-businesses/)
  * [USA to Nigeria Money Transfer Business](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/usa-to-nigeria-money-transfer-business/)
  * [Nigeria: Pre-funding Project](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/nigeria-pre-funding-project/)
  * [MTOs as Cash Out Points App Idea](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/mtos-as-cash-out-points-app-idea/)
  * [Somali MTOs in Minnesota – The Turkey Option!](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/somali-mtos-in-minnesota-the-turkey-option/)
  * [Naira Parallel Market Rate and Money Transfer](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/naira-parallel-market-rate-and-money-transfer/)
  * [How Do You Defeat Or Work With A Parallel Market Rate?](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/how-do-you-defeat-or-work-with-a-parallel-market-rate/)
  * [Revenue Modeling Google Sheet for Remittances – Simplex and Complex](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/revenue-modeling-google-sheet-for-remittances-simplex-and-complex/)
  * [Financial Modeling For The Money Transfer Business](https://faisalkhan.com/video/how-to-start-a-money-transfer-business-video-series/financial-modeling-for-the-money-transfer-business/)
  * [Some hurdles to consider when starting a money transfer business to Nigeria](https://www.youtube.com/watch?v=Mh92E5ow-Ws)