---
title: "Money Transmitter License Information & Requirements by State"
date: "2023-10-08"
url: "/solutions/licensing/money-transmitter-license-mtl/money-transmitter-license-information-requirements-by-state/"
draft: false
description: "* [Alabama Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/alabama-money-transmitter-license/)
  *..."
---

* [Alabama Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/alabama-money-transmitter-license/)
  * [Alaska Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/alaska-money-transmitter-license/)
  * [Arizona Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/arizona-money-transmitter-license/)
  * [Arkansas Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/arkansas-money-transmitter-license/)
  * [California Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/money-transmitter-license-california/)
  * [Colorado Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/colorado-money-transmitter-license/)
  * [Connecticut Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/connecticut-money-transmitter-license/)
  * [Delaware Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/delaware-money-transmitter-license/)
  * [Florida Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/money-transmitter-license-florida/)
  * [Georgia Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/money-transmitter-license-georgia-a-guide/)
  * [Guam Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/guam-money-transmitter-license/)
  * [Hawaii Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/hawaii-money-transmitter-license/)
  * [Idaho Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/idaho-money-transmitter-license/)
  * [Illinois Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/money-transmitter-license-illinois-guide/)
  * [Indiana Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/indiana-money-transmitter-license/)
  * [Iowa Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/iowa-money-transmitter-license/)
  * [Kansas Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/kansas-money-transmitter-license/)
  * [Kentucky Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/kentucky-money-transmitter-license/)
  * [Louisiana Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/louisiana-money-transmitter-license/)
  * [Maine Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/maine-money-transmitter-license/)
  * [Maryland Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/maryland-money-transmitter-license/)
  * [Massachusetts Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/money-transmitter-license-massachusetts/)
  * [Michigan Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/michigan-money-transmitter-license/)
  * [Minnesota Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/minnesota-money-transmitter-license/)
  * [Mississippi Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/mississippi-money-transmitter-license/)
  * [Missouri Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/missouri-money-transmitter-license/)
  * [Nevada Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/money-transmitter-license-nevada/)
  * [New Jersey Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/money-transmitter-license-new-jersey/)
  * [New York Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/money-transmitter-license-new-york/)
  * [Nebraska Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/nebraska-money-transmitter-license/)
  * [New Hampshire Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/new-hampshire-money-transmitter-license/)
  * [New Mexico Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/new-mexico-money-transmitter-license/)
  * [North Carolina Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/north-carolina-money-transmitter-license/)
  * [North Dakota Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/north-dakota-money-transmitter-license/)
  * [Ohio Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/ohio-money-transmitter-license/)
  * [Oklahoma Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/oklahoma-money-transmitter-license/)
  * [Oregon Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/oregon-money-transmitter-license/)
  * [Pennsylvania Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/pennsylvania-money-transmitter-license/)
  * [Puerto Rico Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/money-transmitter-license-puerto-rico/)
  * [Rhode Island Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/rhode-island-money-transmitter-license/)
  * [South Carolina Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/south-carolina-money-transmitter-license/)
  * [South Dakota Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/south-dakota-money-transmitter-license/)
  * [Tennessee Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/tennessee-money-transmitter-license/)
  * [Texas Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/money-transmitter-license-texas/)
  * [Utah Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/utah-money-transmitter-license/)
  * [Vermont Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/vermont-money-transmitter-license/)
  * [Virginia Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/virginia-money-transmitter-license/)
  * [Virgin Islands Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/virgin-islands-money-transmitter-license/)
  * [West Virginia Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/west-virginia-money-transmitter-license/)
  * [Wisconsin Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/wisconsin-money-transmitter-license/)
  * [Wyoming Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/wyoming-money-transmitter-license/)
  * [Washington Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/money-transmitter-license-washington/)
  * [Washington DC Money Transmitter License](https://faisalkhan.com/solutions/licensing/money-transmitter-license-mtl/money-transmitter-license-washington-dc/)